# Generated by Django 5.1.3 on 2024-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logout_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
